### ISSUE TITLE
找不到com.facebook.react.devsupport.JSException: Can't find variable: __d

### ISSUE THREAD

**Issue by lufan6** [smallnew/react-native-multibundler#24]
Process: com.yuebaoxiaov2, PID: 31654
    java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Can't find variable: __d
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:22)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:170)
        at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:547)
        at com.facebook.react.bridge.CatalystInstanceImpl.access$1000(CatalystInstanceImpl.java:44)
        at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:563)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.facebook.react.devsupport.JSException: Can't find variable: __d
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: com.facebook.jni.CppException: Can't find variable: __d
    
    global code@index.android.bundle:2:4

**Comment by liyanfei1004774105** [comment]
耶耶耶耶耶

**Comment by star-heng** [comment]
这个是bundle文件没打好?

**Comment by lufan6** [comment]
java.lang.RuntimeException: Unable to resume activity {com.jiajiantech.dzfpj/com.jiajiantech.dzfpj.ui.InvoiceActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onHostResume()' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4190)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4222)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7319)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.ReactDelegate.onHostResume()' on a null object reference
at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:97)
at com.facebook.react.AsyncReactActivity.onResume(AsyncReactActivity.java:234)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
at android.app.Activity.performResume(Activity.java:7920)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4180)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4222) 
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
at android.os.Handler.dispatchMessage(Handler.java:107) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:7319) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934) 
你好 问一下 我这个升级以后 没有提前加载业务包报错 知道什么原因吗？ 谢谢



在 2019-09-16 09:44:56，"star-heng" <notifications@github.com> 写道：

这个是bundle文件没打好?
