### ISSUE TITLE
安卓打包release空指针

### ISSUE THREAD

**Issue by xmuSistone** [smallnew/react-native-multibundler#35]
RN拆包，debug是完全OK的，但是release爆了空指针异常，大概是什么问题呢？
```xml
java.lang.NullPointerException: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6707)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
     Caused by: java.lang.NullPointerException: java.lang.NullPointerException
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:224)
        at club.fromfactory.baselibrary.utils.RNScriptLoadUtil.loadFile(RNScriptLoadUtil.java:78)
        at club.fromfactory.baselibrary.utils.RNScriptLoadUtil.loadScriptFromFile(RNScriptLoadUtil.java:54)

```

**Comment by xmuSistone** [comment]
额，没问题了，是我们loadScript调用流程疏忽，导致CatalystInstanceImpl被destroy了。
