### ISSUE TITLE
com.facebook.jni.CppException: Can't find variable: __d

### ISSUE THREAD

**Issue by star-heng** [smallnew/react-native-multibundler#55]
```
 E/unknown:ReactNative: Exception in native call
    com.facebook.jni.CppException: Can't find variable: __d
    
    global code@index.android.bundle:1:4
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by star-heng** [comment]
这个是bundle文件没有打好?

**Comment by smallnew** [comment]
可能是没有加载基础包就加载了业务包

**Comment by star-heng** [comment]
@smallnew  这边打的基础报有1M多点, 然后业务包有3M多点. 按照你的demo里面的用法, 就报这个错
