### ISSUE TITLE
CatalystInstance.loadScriptFromAssets(android.content.res.AssetManager, java.lang.String, boolean)' on a null object reference

### ISSUE THREAD

**Issue by star-heng** [smallnew/react-native-multibundler#58]
```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.CatalystInstance.loadScriptFromAssets(android.content.res.AssetManager, java.lang.String, boolean)' on a null object reference
    at com.facebook.react.BridgeUtil.loadScriptFromAsset(BridgeUtil.java:18)
    at com.facebook.react.ScriptLoadUtil.loadScriptFromAsset(ScriptLoadUtil.java:93)
    at com.facebook.react.AsyncReactActivity.loadScript(AsyncReactActivity.java:89)
    at com.facebook.react.AsyncReactActivity.onCreate(AsyncReactActivity.java:71)
    at com.heng.project.MainActivity.onCreate(MainActivity.java:129)
    at android.app.Activity.performCreate(Activity.java:6833)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
    ... 9 more
```

**Comment by star-heng** [comment]
release包中出现的

**Comment by star-heng** [comment]
这个问题出现的原因: ReactContext没有实例化.
场景是这样的: 在有些手机上 createReactContextInBackground这个方法还没有执行完程序就已经走到 
AsyncReactActivity中的 loadScript方法了, 然后报 context is null!!
解决办法: demo中的MainActivity的onCreate方法里面不要执行 createReactContextInBackground
